### ISSUE TITLE
Is there a patch for netsnmp 5.7.x versions to use large FD set in snmp client?

### ISSUE THREAD

**Issue by Ymitrofanov** [net-snmp/net-snmp#218]
Hello!

We have an issue on RedHat 7.8 with netsnmp 5.7.2 when snmp client hangs if FD has a value which is more than 1024.
I understood this when I checked AgentX connection socket FD which was more than 1024, and also I investigated 'snmp_synch_response_cb' function in snmp_client.c which invokes 'select' function which is limited with 1024.
I compared sources of netsnmp 5.7.2 version from RedHat packet and sources of netsnmp 5.8 which I downloaded from official site. I found the difference in snmp_synch_response_cb - in 5.8 it invokes 'netsnmp_large_fd_set_select', but in 5.7.2 it invokes 'select'. I also found some other places in 5.8 client source code where functions which relate to large FD set are called.
When I installed netsnmp 5.8 and recompiled the client application with libnetsnmp 5.8 and restarted my application and snmpd - issue has gone.
We are using netsnmp 5.7.2 on Linux RedHat 7.8 and unfortunately currently we cannot upgrade netsnmp to next release version because of libnetsnmp dependencies in some third-party appplications.

So, my question is - is it possible to patch 5.7.2 version to fix large FD issue, or we should use 5.8 or latest releases?

Thank you in advance!

**Comment by jridky** [comment]
Well, you have basically several options, how to deal with this issue.

1. Update to RHEL-8, where net-snmp-5.8 version is available and this issue is solved.
2. Contact Red Hat Support with request to fix this issue in RHEL-7.9.
3. Cherry pick the necessary changes from upstream and fix it and build it yourself. As good start point, you can take look at [this commit](https://github.com/net-snmp/net-snmp/commit/0e76b6ebb9f3e1c867fb2c0126ed1ee6da624368). 
4. Download current upstream version of net-snmp, build it and install it to your system.

Be aware, if you have active subscription for your RHEL, by choosing points 3 or 4 you automatically looses support from Red Hat, because you'll be doing your own system customization.

Regards
Josef

**Comment by Ymitrofanov** [comment]
Hi Josef.
Thank you for the reply!
We'll think about which option is most applicable.
Thanks!
