### ISSUE TITLE
SNMP hrStorage limited

### ISSUE THREAD

**Issue by sargenthp** [net-snmp/net-snmp#508]
SNMP is limited for the Storage space available these days being that we are stuck with an INTEGER type for hrStorageSize, hrStorageUsed, and hrPartitionSize.  Any plans to move to a DOUBLE for this number (preferably unsigned double)?

For an AIX  and Linux server with hrStorageAllocationUnits of 4096 Bytes is a max of just under 16TB.
      4,294,967,295 * 4096 / 1024 / 1024 / 1024 / 1024 = 15.99999999627470 TB

We currently have servers with 27TB disks.

Thank you

**Comment by nielsb** [comment]
The HOST-RESOURCES-MIB is defined by the IETF, so we cannot change that, but the hrStorageTable should give you the proper size because it will fake the hrStorageAllocationUnits to 8192 to make hrStorageSize fit in the 32 bits.

Unless of course you have set realStorageUnits to 1 in snmpd.conf?

/Niels

**Comment by sargenthp** [comment]
Okay.  Looks like we are actually OK on the Linux servers.  It is the AIX
servers we are having trouble with.  Going to harass them more.

Thank you.
