### ISSUE TITLE
ASN.1 Long Length Form incorrectly used, 10% reduction in packet size possible 

### ISSUE THREAD

**Issue by upsampled** [net-snmp/net-snmp#717]
I was writing validation tests for `gosnmp\gosnmp` against `net-snmp` (gosnmp/gosnmp#448) and I noticed a discrepancy in ASN.1 headers. Specifically, `net-snmp` was constantly using the [Long Form for ASN.1 Length Encoding](https://www.oss.com/asn1/resources/asn1-made-simple/asn1-quick-reference/basic-encoding-rules.html#:~:text=rightmost%20seven%20bits.-,Long%20form,-%3A%20for%20lengths%20between) when `gosnmp\gosnmp` was using Short Form. After reading the ASN.1 standard more, it does seem that Long Form should only be use for lengths greater than `0x80` and it seems like the majority of `net-snmp` ASN.1 functions enforce this [rule ](https://github.com/net-snmp/net-snmp/blob/54afce7565a62ac3db61362328b682e8d10a4aa9/snmplib/asn1.c#L1382C7-L1382C7). The issue seems to lie with `asn_build_sequence` which only uses the Long Form. 

```c
u_char         *
asn_build_sequence(u_char * data,
                   size_t * datalength, u_char type, size_t length)
{
    static const char *errpre = "build seq";
    char            ebuf[128];

    if (*datalength < 4) {
        snprintf(ebuf, sizeof(ebuf),
                "%s: length %d < 4: PUNT", errpre,
                (int) *datalength);
        ebuf[ sizeof(ebuf)-1 ] = 0;
        ERROR_MSG(ebuf);
        return NULL;
    }
    *datalength -= 4;
    *data++ = type;
    *data++ = (u_char) (0x02 | ASN_LONG_LEN);
    *data++ = (u_char) ((length >> 8) & 0xFF);
    *data++ = (u_char) (length & 0xFF);
    return data;
}
```

In my simple validation test, by using the short form, I am seeing a %10 reduction in packet size.

**Comment by hardaker** [comment]
Hi unsampled,

Yes you're right that there is a function called `asn_build_sequence` that uses a long form.  It does this because when building the packet forward it doesn't know the length of the following data and thus must reserve extra room in the length field in case the packet is longer than can fit in a single byte length field.  Or else it would have to move a lot of memory around to make the room later.  This function dates back the original CMU-SNMP code that Net-SNMP started from way way back.

But, none of the Net-SNMP tools use this function by default.  We actually build packets in reverse by default to avoid both the increased length field and/or having to move memory around.  The function that does this is called `asn_rbuild_sequence` instead.  You can see this by using the tools and trying both the forward and backwards encodings (the default being backwards):

```
$ snmpgetnext -d localhost .1.3

Sending 64 bytes to UDP: [127.0.0.1]:161->[0.0.0.0]:53609
0000: 30 3E 02 01  03 30 11 02  04 50 46 88  10 02 03 00    0>...0...PF.....
0016: FF E3 04 01  04 02 01 03  04 10 30 0E  04 00 02 01    ..........0.....
0032: 00 02 01 00  04 00 04 00  04 00 30 14  04 00 04 00    ..........0.....
0048: A0 0E 02 04  0C D6 8A 26  02 01 00 02  01 00 30 00    .......&......0.
```

forwards is less efficient and takes more bytes (as you've noticed):

```
$ snmpgetnext --reverseEncodeBER=no -d localhost .1.3

Sending 76 bytes to UDP: [127.0.0.1]:161->[0.0.0.0]:52603
0000: 30 82 00 48  02 01 03 30  82 00 11 02  04 64 0D 5E    0..H...0.....d.^
0016: 72 02 03 00  FF E3 04 01  04 02 01 03  04 12 30 82    r.............0.
0032: 00 0E 04 00  02 01 00 02  01 00 04 00  04 00 04 00    ................
0048: 30 82 00 18  04 00 04 00  A0 82 00 10  02 04 55 ED    0.............U.
0064: B6 8E 02 01  00 02 01 00  30 82 00 00                 ........0...
```

**Comment by upsampled** [comment]
Gotcha, I am just using `snmp_build` directly so i think my issue is the following code is forcing forward encoding:

```c
    if ((pdu->flags & UCD_MSG_FLAG_BULK_TOOBIG) ||
        (0 == netsnmp_ds_get_boolean(NETSNMP_DS_LIBRARY_ID,
                                     NETSNMP_DS_LIB_REVERSE_ENCODE))) {
        pdu->flags |= UCD_MSG_FLAG_FORWARD_ENCODE;
    }
```

Thank you for your help!

**Comment by upsampled** [comment]
Fixed by adding the following (the `C.` is just go-c bindings):

```go
	C.netsnmp_ds_set_boolean(C.NETSNMP_DS_LIBRARY_ID,
		C.NETSNMP_DS_LIB_REVERSE_ENCODE,
		C.NETSNMP_DEFAULT_ASNENCODING_DIRECTION)
```
